version: '3.7'

x-phoenix: &phoenix
  image: [project_name]:latest-test
  build:
    context: .
    dockerfile: Dockerfile.test
  links:
  - db
  volumes:
  - test-plts:/app/priv/plts
  environment:
    DATABASE_PASSWORD: postgres
    DATABASE_HOSTNAME: db

services:
  app:
    <<: *phoenix
    command: mix phx.server
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

volumes:
  test-plts: