FROM elixir:1.15.6

RUN apt-get update && \
    apt-get install -y \
      git \
      wget \
      curl \
      npm \
      ca-certificates \
      apt-transport-https \
      gnupg \
      lsb-release \
      freetds-dev \
      inotify-tools && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# Install LTS of nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs

ENV MIX_ENV dev
ENV NODE_ENV development

# Install Yarn
RUN npm install -g yarn

# Ensure latest versions of Hex/Rebar are installed on build
RUN mix do local.hex --force, local.rebar --force
    # mix archive.install --force hex phx_new 1.5.9

RUN mkdir /app
WORKDIR /app