FROM elixir:1.16.0

RUN apt-get update && \
    apt-get install -y \
      make \
      g++ \
      git \
      wget \
      curl \
      npm \
      freetds-dev \
      inotify-tools && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV MIX_ENV dev
ENV NODE_ENV development

# Install LTS of nodejs and yarn
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs && \ 
    npm install -g yarn

ENV MIX_ENV test
ENV NODE_ENV development

# Ensure latest versions of Hex/Rebar are installed on build
RUN mix do local.hex --force, local.rebar --force

RUN mkdir /app
WORKDIR /app

# Install deps
COPY mix.exs mix.lock ./
COPY config config
RUN mix deps.get && \
    mix deps.compile

# Install assets
COPY assets assets
RUN yarn --cwd assets install

COPY priv priv
COPY lib lib
COPY test test
COPY .formatter.exs .formatter.exs
# COPY .dialyzer_ignore.exs .dialyzer_ignore.exs
COPY .credo.exs .credo.exs
RUN mix compile

